name: Build on push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    name: Build
    strategy:
      matrix:
        build_type: [ Debug, Release, RelWithDebInfo ]

    steps:
      - uses: actions/checkout@v2

      - name: Install conan
        run: pip install conan

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -A Win32

      - name: Build replayer
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config ${{matrix.build_type}} --target among-us-replayer

      - name: Collect resources
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          cmake -E make_directory _dist
          cmake -E copy bin/among-us-replayer.exe _dist/among-us-replayer.exe
          cmake -E copy_directory "${{github.workspace}}/res" _dist/res

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build_type}}
          path: |
            ${{github.workspace}}/build/_dist
