name: Build On Push

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    name: Build
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        arch: [ Win32, x64 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install conan
        run: pip install conan

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -A ${{matrix.arch}}

      - name: Build replayer
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config ${{matrix.build_type}} --target among-us-replayer

      - name: Collect resources
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          cmake -E make_directory _dist
          cmake -E copy bin/among-us-replayer.exe _dist/among-us-replayer.exe
          cmake -E copy bin/among-us-replayer.pdb _dist/among-us-replayer.pdb
          cmake -E copy_directory "${{github.workspace}}/res" _dist/res
          if [ "${{matrix.arch}}" == "x64" ]; then cmake -E copy_directory "${{github.workspace}}/res_hq" _dist/res; fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.build_type}}-${{matrix.arch}}
          path: |
            ${{github.workspace}}/build/_dist
