name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: Build Release ${{matrix.name}}
    strategy:
      matrix:
        include:
        - name: Windows x86
          archive_suffix: win-32
          os: windows-latest
          cmake_arch: -A Win32
          is_hq: no

        - name: Windows x86-64
          archive_suffix: win-64
          os: windows-latest
          cmake_arch: -A x64
          is_hq: yes

    steps:
      - uses: actions/checkout@v2

      - name: Install conan
        run: pip install conan

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release ${{matrix.cmake_arch}}

      - name: Build replayer
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --target among-us-replayer

      - name: Collect resources
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          cmake -E make_directory among-us-replayer
          cmake -E copy bin/among-us-replayer.exe among-us-replayer/among-us-replayer.exe
          cmake -E copy_directory "${{github.workspace}}/res" among-us-replayer/res
          if [ "${{matrix.is_hq}}" == "yes" ]; then cmake -E copy_directory "${{github.workspace}}/res_hq" among-us-replayer/res; fi
          cmake -E tar cfv among-us-replayer-${{matrix.archive_suffix}}.zip --format=zip among-us-replayer

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: among-us-replayer-${{matrix.archive_suffix}}.zip
          path: ${{github.workspace}}/build/among-us-replayer-${{matrix.archive_suffix}}.zip

  publish:
    needs: build
    runs-on: windows-latest
    name: Publish Release ${{github.ref}}

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: among-us-replayer-win-32.zip

      - uses: actions/download-artifact@v2
        with:
          name: among-us-replayer-win-64.zip

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: |
            among-us-replayer-win-32.zip
            among-us-replayer-win-64.zip
