name: Tagged Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    name: Publish Release ${{github.ref}}
    strategy:
      matrix:
        arch: [ Win32, x64 ]

    steps:
      - uses: actions/checkout@v2

      - name: Install conan
        run: pip install conan

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: |
          cmake .. -DCMAKE_BUILD_TYPE=Release -A ${{matrix.arch}}

      - name: Build replayer
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config Release --target among-us-replayer

      - name: Collect resources
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: |
          cmake -E make_directory among-us-replayer
          cmake -E copy bin/among-us-replayer.exe among-us-replayer/among-us-replayer.exe
          cmake -E copy_directory "${{github.workspace}}/res" among-us-replayer/res
          if [ "${{matrix.arch}}" == "x64" ]; then cmake -E copy_directory "${{github.workspace}}/res_hq" among-us-replayer/res; fi
          cmake -E tar cfv among-us-replayer-${{matrix.arch}}.zip --format=zip among-us-replayer

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: |
            build/among-us-replayer-${{matrix.arch}}.zip
